# from Wikipedia (https://ja.wikipedia.org/wiki/BibTeX)
required = {
    "article": [
        "author",
        "title",
        "journal",
        "year",
        "volume",
        "number",
        "pages",
        "key",
    ],
    "phdthesis": [
        "author",
        "title",
        "school",
        "year",
        "address",
        "month",
        "note",
        "key",
    ],
    "masterthesis": [
        "author",
        "title",
        "school",
        "year",
        "address",
        "month",
        "note",
        "key",
    ],
    "proceedings": [
        "title",
        "year",
        "editor",
        "publisher",
        "organization",
        "address",
        "month",
        "note",
        "key",
        "volume",
        "number",
    ],
    "inproceedings": ["author", "title", "booktitle", "year", "pages", "key"],
    "conference": [
        "author",
        "title",
        "booktitle",
        "year",
        "editor",
        "pages",
        "organization",
        "publisher",
        "address",
        "month",
        "note",
        "key",
    ],
    "book": [
        "author",
        "title",
        "publisher",
        "year",
        "volume",
        "series",
        "edition",
        "key",
    ],
    "booklet": [
        "title",
        "author",
        "howpublished",
        "address",
        "month",
        "year",
        "note",
        "key",
    ],
    "inbook": [
        "author",
        "editor",
        "title",
        "chapter",
        "pages",
        "publisher",
        "year",
        "volume",
        "series",
        "address",
        "edition",
        "month",
        "note",
        "key",
    ],
    "incollection": [
        "author",
        "title",
        "booktitle",
        "year",
        "editor",
        "pages",
        "organization",
        "publisher",
        "address",
        "month",
        "note",
        "key",
    ],
    "manual": [
        "title",
        "author",
        "organization",
        "address",
        "edition",
        "month",
        "year",
        "note",
        "key",
    ],
    "techreport": [
        "author",
        "title",
        "institution",
        "year",
        "type",
        "number",
        "address",
        "month",
        "note",
        "key",
    ],
    "misc": ["author", "title", "howpublished", "month", "year", "note", "key"],
    "unpublished": ["author", "title", "note", "month", "year", "key"],
}
